# Generated by Django 5.2.4 on 2025-07-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.FloatField(blank=True, help_text="Latitude of the client's residence", null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.FloatField(blank=True, help_text="Longitude of the client's residence", null=True),
        ),
    ]
