# Generated by Django 5.2.4 on 2025-07-20 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_code',
            field=models.CharField(blank=True, help_text='6-digit code for app login (optional)', max_length=6, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_login_code', message='Login code must be exactly 6 digits.', regex='^[0-9]{6}$')]),
        ),
    ]
