# Generated by Django 5.2.4 on 2025-07-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_login_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biometric_id',
            field=models.CharField(blank=True, help_text='Unique biometric identifier for fingerprint/face recognition (optional)', max_length=255, null=True, unique=True),
        ),
    ]
