# Generated by Django 5.2.4 on 2025-07-23 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('start', 'Start'), ('end', 'End'), ('deviation', 'Deviation')], max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('distance_from_client', models.FloatField(help_text='Distance from client residence in meters')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='appointment_management.appointment')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
